# Generated by Django 3.1.7 on 2021-03-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post_type', models.CharField(max_length=30)),
                ('post_text', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=255)),
                ('theme_month', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('theme_hashtag', models.TextField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_english', models.TextField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('verse_image', models.ImageField(upload_to='upload/verse_images/')),
                ('verse_date', models.DateField()),
                ('verse_french', models.TextField(max_length=255)),
                ('verse_kirundi', models.TextField(max_length=255)),
                ('verse_hashtag', models.TextField(max_length=255)),
            ],
        ),
    ]
