# Generated by Django 3.1.7 on 2021-04-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True)),
                ('english', models.TextField(blank=True, max_length=255)),
                ('hashtag', models.TextField(blank=True, max_length=255)),
                ('post_type', models.CharField(blank=True, max_length=30)),
                ('post_text', models.TextField(max_length=255)),
                ('french', models.TextField(blank=True, max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('kirundi', models.TextField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('theme_from_date', models.DateField(blank=True)),
                ('theme_hashtag', models.TextField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('theme_to_date', models.DateField(blank=True)),
                ('theme', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='post_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('post_image', models.ImageField(blank=True, upload_to='upload/post_pre_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
    ]
