# Generated by Django 3.1.7 on 2021-03-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='qoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('qoute_date', models.DateField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('qoute_image', models.ImageField(blank=True, upload_to='upload/qoute_images/')),
                ('qoute_hashtag', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='upload/post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_hashtag',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_month',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_english',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_french',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_hashtag',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_image',
            field=models.ImageField(blank=True, upload_to='upload/verse_images/'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_kirundi',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
